name: RabbitMQ CI Workflow

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'the version'
                required: true
                type: string
                default: ''

jobs:
    Display-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display User Inputs
              id: display-user-inputs
              run: |
                echo "User Inputs:"
                echo "${{ toJSON(github.event.inputs) }}"

    in-and-out:
        runs-on: ubuntu-latest
        needs: Display-inputs
        outputs:
            OUTPUT1: testy
        steps:
            - name: Display User Inputs
              id: display-user-inputs
              run: |
                echo "Version input: ${{inputs.version}}"
            - name: Set Outputs
              id: set-outputs
              run: |
                  echo "Version input: ${{inputs.version}}"

    final-steop:
        runs-on: ubuntu-latest
        needs: in-and-out
        steps:
            - name: Display User Inputs
              id: display-user-inputs
              run: |
                echo "Version input: ${{needs.in-and-out.outputs.OUTPUT1}}"
