name: RabbitMQ CI Workflow

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'the version'
                required: true
                type: string
                default: ''

# ENV Vars can be at top level, job level, or step level
env: 
  DAY_OF_WEEK: Monday

jobs:
    Display-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: Display User Inputs
              id: display-user-inputs
              run: |
                echo "User Inputs:"
                echo "${{ toJSON(github.event.inputs) }}"

    in-and-out:
        runs-on: ubuntu-latest
        needs: Display-inputs
        outputs:
            OUTPUT1: ${{ steps.set-outputs.outputs.JUMPERBOX_IP }}
        steps:
            - name: Display Version Input
              id: display-version-inputs
              run: |
                echo "Version input: ${{inputs.version}}"
                echo "Day of week: $DAY_OF_WEEK"
                echo "$GITHUB_ENV"
            - name: Set Outputs
              id: set-outputs
              run: |
                  echo "JUMPERBOX_IP=HOSTNAME" >> $GITHUB_OUTPUT

    final-step:
        runs-on: ubuntu-latest
        needs: in-and-out
        steps:
            - name: Display User Inputs
              id: display-user-inputs
              run: |
                echo "Output1: ${{needs.in-and-out.outputs.OUTPUT1}}"
                echo "Best regards," >> $GITHUB_STEP_SUMMARY
                # use upload artifact and download artifact to pass artifacts
